# permissions for end users to view releasers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaser-viewer-role
rules:
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasers/status
  verbs:
  - get
