# permissions for end users to edit releasers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releaser-editor-role
rules:
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasers/status
  verbs:
  - get
